# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Update a Vulnogram CVE record over the API.

Replaces the release-manager copy-paste flow: open ``#source``, paste
the JSON, click *Save*. Reads the JSON from a file (typically the
``cve-json/<CVE-ID>.json`` artefact regenerated by
``generate-cve-json``), POSTs it to ``/cve5/<CVE-ID>``, and surfaces
the Vulnogram envelope verbatim.

State transitions (``DRAFT`` → ``REVIEW`` → ``READY`` → ``PUBLIC``)
are **not** driven by this script. Vulnogram's state machine lives in
the ``CNA_private.state`` field of the document body — flipping it
through the API path simply means setting the field in the JSON
before calling this script. The actual publish-to-cve.org push
(``READY`` → ``PUBLIC``) still happens through the Vulnogram UI button
because it has out-of-band side effects (CNA feed dispatch) that the
script intentionally does not automate.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from vulnogram_api.client import (
    CSRFNotFound,
    RecordSaveFailed,
    SessionExpired,
    VulnogramAPIError,
    update_record,
)
from vulnogram_api.credentials import Session, locate_session

CVE_ID_RE = re.compile(r"^CVE-\d{4}-\d{4,7}$")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description=(__doc__ or "").split("\n\n", 1)[0],
    )
    ap.add_argument(
        "--cve-id",
        required=True,
        help="The CVE ID, e.g. CVE-2026-12345.",
    )
    ap.add_argument(
        "--json-file",
        required=True,
        help=(
            "Path to the CVE JSON document — typically the file "
            "`generate-cve-json --out` produced, or the JSON "
            "embedded in the tracker body."
        ),
    )
    ap.add_argument(
        "--credentials",
        default=None,
        help=(
            "Path to the session JSON. Defaults to "
            "$VULNOGRAM_SESSION, else "
            "~/.config/apache-steward/vulnogram-session.json."
        ),
    )
    ap.add_argument(
        "--section",
        default="cve5",
        help="Vulnogram section path component. Default: cve5.",
    )
    return ap.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if not CVE_ID_RE.match(args.cve_id):
        raise SystemExit(f"--cve-id {args.cve_id!r} does not match CVE-YYYY-NNNN form. Refusing to POST.")

    json_path = Path(args.json_file).expanduser()
    if not json_path.is_file():
        raise SystemExit(f"--json-file not found: {json_path}")

    try:
        document = json.loads(json_path.read_text())
    except json.JSONDecodeError as e:
        raise SystemExit(f"--json-file is not valid JSON: {e}") from e
    if not isinstance(document, dict):
        raise SystemExit(f"--json-file top-level value is not a JSON object: {type(document).__name__}")

    creds_path = locate_session(args.credentials)
    session = Session.load(creds_path)

    try:
        envelope = update_record(session, args.cve_id, document, section=args.section)
    except SessionExpired as e:
        print(f"✗ {e}", file=sys.stderr)
        return 2
    except CSRFNotFound as e:
        print(f"✗ {e}", file=sys.stderr)
        return 4
    except RecordSaveFailed as e:
        print(f"✗ {e}", file=sys.stderr)
        return 5
    except VulnogramAPIError as e:
        print(f"✗ {e}", file=sys.stderr)
        return 6

    if envelope.get("type") == "saved":
        print(f"✓ {args.cve_id} saved at https://{session.host}/{args.section}/{args.cve_id}")
        return 0
    if envelope.get("type") == "go":
        print(
            f"✓ {args.cve_id} saved; Vulnogram redirected to "
            f"{envelope.get('to')!r} (record was renamed mid-save)."
        )
        return 0
    print(f"? Unexpected envelope shape: {envelope}", file=sys.stderr)
    return 7


if __name__ == "__main__":
    raise SystemExit(main())
